name: Release
# good pnpm examples: https://github.com/withastro/astro/tree/main/.github/workflows
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changelog:
    name: Changelog PR or Release
    if: ${{ github.repository_owner == 'evatrium' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          # Note: pnpm install after versioning is necessary to refresh lockfile
          version: pnpm run version
          publish: pnpm exec changeset publish
          commit: '[ci] release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate Notification
        id: notification
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: echo 'doneskis'
